import type { Item } from '../types';

const zone = 'control-room' as const;

// No numbers are needed in this zone, so every fact below is a description. Anything beyond SPEC §8 is general, not measured.
export const controlRoomItems: Item[] = [
  {
    id: 'control-tower',
    zone,
    kind: 'object',
    number: 1,
    name: 'Control tower',
    aliases: ['DCGM', 'Data Center GPU Manager', 'monitoring', 'telemetry'],
    category: 'Operations',
    metaphor: 'The tower on the hill with screens that watch the whole town',
    swatch: 'scene-roof',
    summary:
      'DCGM (Data Center GPU Manager) collects health and performance readings from every GPU in the cluster: how busy each one is, how hot, how much power and memory it uses, and whether anything is failing. Sensor lines run from the tower to every district, so the people on the hill see problems early.',
    facts: [
      { label: 'Tool', value: 'DCGM, NVIDIA Data Center GPU Manager' },
      { label: 'Reports', value: 'Utilization, SM activity, memory, temperature, power, health' },
    ],
    related: ['nvidia-smi', 'utilization-trap', 'cluster-manager', 'workload-management'],
    anchorId: 'control-tower',
  },
  {
    id: 'dispatcher-desk',
    zone,
    kind: 'object',
    number: 2,
    name: 'Dispatcher desk',
    aliases: ['Slurm', 'job scheduler', 'batch scheduler', 'queue'],
    category: 'Scheduling',
    metaphor: 'A desk with a board of tickets: each job waits its turn for machines',
    swatch: 'scene-hall',
    summary:
      'Slurm is a job scheduler for clusters. People submit a job with what it needs, such as how many GPUs and for how long. Slurm queues it, finds free machines, starts it and frees the machines when it ends. It suits long training runs that need a block of machines to themselves.',
    facts: [
      { label: 'Does', value: 'Queues jobs and hands out whole machines' },
      { label: 'Typical home', value: 'Research and training clusters' },
    ],
    compare: {
      with: ['Kubernetes'],
      rows: [
        { label: 'In the factory', values: ['Desk with tickets', 'Yard with cranes'] },
        { label: 'Unit of work', values: ['A batch job that ends', 'A container that can run for ever'] },
        { label: 'Best for', values: ['Training runs queued for a block of GPUs', 'Always-on services and many small workloads'] },
        { label: 'Familiar to', values: ['HPC and research teams', 'Cloud and platform teams'] },
      ],
      fullCompareId: 'slurm-vs-kubernetes',
    },
    related: ['container-yard', 'workload-management', 'cluster-manager', 'training-line'],
    anchorId: 'dispatcher-desk',
  },
  {
    id: 'partitioned-hall',
    zone,
    kind: 'object',
    number: 3,
    name: 'Partitioned hall',
    aliases: ['MIG', 'Multi-Instance GPU', 'GPU partitioning'],
    category: 'GPU sharing',
    metaphor: 'A production hall split into rooms by real walls',
    swatch: 'scene-network',
    summary:
      'MIG (Multi-Instance GPU) splits one GPU into several smaller GPUs in hardware. Each slice gets its own SMs and its own share of memory, so jobs run at the same time and one job cannot slow down or crash another. It arrived with the Ampere generation.',
    facts: [
      { label: 'Split by', value: 'Hardware walls: own SMs and memory per slice' },
      { label: 'Introduced with', value: 'Ampere' },
    ],
    compare: {
      with: ['Time-slicing', 'vGPU'],
      rows: [
        { label: 'In the factory', values: ['Walls', 'Shift schedule', 'Rented booths'] },
        { label: 'Jobs run', values: ['At the same time', 'One after another', 'Taking turns, per virtual GPU'] },
        { label: 'Isolation', values: ['Strong, in hardware', 'None', 'Strong, set by the hypervisor'] },
      ],
      fullCompareId: 'gpu-sharing',
    },
    related: ['shift-hall', 'vgpu', 'utilization-trap', 'sm'],
    anchorId: 'partitioned-hall',
    shareSim: { sharing: 'mig' },
  },
  {
    id: 'shift-hall',
    zone,
    kind: 'object',
    number: 4,
    name: 'Shift-scheduled hall',
    aliases: ['time-slicing', 'time slicing', 'GPU time-sharing'],
    category: 'GPU sharing',
    metaphor: 'One big hall where each team gets a shift on the whole floor',
    swatch: 'scene-hall',
    summary:
      'With time-slicing, several jobs share one GPU by taking turns: each runs on the whole GPU for a short slice, then steps aside for the next. It is easy to set up and works on any GPU, but each job only gets a fraction of the time, nothing walls the jobs off from each other, and one hungry job can slow the rest.',
    facts: [
      { label: 'Split by', value: 'Time: jobs take turns on the whole GPU' },
      { label: 'Isolation', value: 'None between jobs' },
    ],
    related: ['partitioned-hall', 'vgpu', 'utilization-trap', 'nvidia-smi'],
    anchorId: 'shift-hall',
    shareSim: { sharing: 'time-slicing' },
  },
  {
    id: 'container-yard',
    zone,
    kind: 'object',
    number: 5,
    name: 'Container yard',
    aliases: ['Kubernetes', 'K8s', 'containers', 'orchestration'],
    category: 'Scheduling',
    metaphor: 'A yard where cranes keep moving containers to wherever there is room',
    swatch: 'scene-storage',
    summary:
      'Kubernetes runs software packed in containers across many machines. It places each container where there is room, restarts it when it fails and moves it when a machine goes away. With a GPU plug-in it can hand GPUs to containers, which makes it the usual home for always-on inference services.',
    facts: [
      { label: 'Does', value: 'Places, restarts and scales containers' },
      { label: 'Typical home', value: 'Always-on services and inference' },
    ],
    compare: {
      with: ['Slurm'],
      rows: [
        { label: 'In the factory', values: ['Yard with cranes', 'Desk with tickets'] },
        { label: 'Unit of work', values: ['A container that can run for ever', 'A batch job that ends'] },
        { label: 'Best for', values: ['Always-on services and many small workloads', 'Training runs queued for a block of GPUs'] },
      ],
      fullCompareId: 'slurm-vs-kubernetes',
    },
    related: ['dispatcher-desk', 'workload-management', 'mlops', 'shipping-dock'],
    anchorId: 'container-yard',
  },
  {
    id: 'cluster-manager',
    zone,
    kind: 'object',
    number: 6,
    name: 'Cluster manager',
    aliases: ['Base Command Manager', 'BCM', 'cluster provisioning'],
    category: 'Operations',
    metaphor: 'The office with a wall of status screens for every machine',
    swatch: 'scene-network',
    summary:
      'Base Command Manager sets up and looks after a whole cluster: it installs software on new machines, keeps configurations in step, shows the state of every node and can work with a job scheduler. It is the office that makes a pile of servers behave like one factory.',
    facts: [{ label: 'Does', value: 'Provisions, configures and monitors cluster nodes' }],
    related: ['control-tower', 'dispatcher-desk', 'dgx-node', 'workload-management'],
    anchorId: 'cluster-manager',
  },
  {
    id: 'vgpu',
    zone,
    kind: 'concept',
    name: 'vGPU',
    aliases: ['virtual GPU', 'GPU virtualization'],
    category: 'GPU sharing',
    metaphor: 'Booths rented out by the hour, each with a fixed share of the machine',
    summary:
      'vGPU lets a hypervisor carve one physical GPU into virtual GPUs and hand each to a virtual machine. Each virtual GPU gets a fixed share and its own memory, and the hypervisor takes turns between them. It suits shared desktops and virtual machines more than the largest training jobs.',
    facts: [
      { label: 'Split by', value: 'The hypervisor, per virtual machine' },
      { label: 'Isolation', value: 'Strong, between virtual machines' },
    ],
    related: ['partitioned-hall', 'shift-hall', 'nvidia-smi'],
    shareSim: { sharing: 'vgpu' },
  },
  {
    id: 'nvidia-smi',
    zone,
    kind: 'concept',
    name: 'nvidia-smi',
    aliases: ['SMI', 'System Management Interface'],
    category: 'Operations',
    metaphor: 'A quick glance through the window of one machine',
    summary:
      'nvidia-smi is the command-line tool that shows the state of the GPUs in one machine: what is running, how much memory is in use, temperature and power, and a utilization percentage. It is the first thing most people reach for, which is why its utilization number is so often misread.',
    facts: [{ label: 'Shows', value: 'Per-machine GPU status, including utilization' }],
    related: ['utilization-trap', 'control-tower', 'shift-hall'],
  },
  {
    id: 'utilization-trap',
    zone,
    kind: 'concept',
    name: 'The 100% utilization trap',
    aliases: ['GPU utilization', 'SM activity', 'utilization'],
    category: 'Operations',
    metaphor: 'A hall with the lights on and one worker inside',
    summary:
      'GPU utilization only says that something was running on the GPU. It does not say how much of the GPU was used. A small job can keep one tiny corner busy and still show 100% utilization while most of the SMs sit idle. SM activity, which DCGM can report, counts the SMs that were actually working. Watch both before concluding that a GPU is full.',
    facts: [
      { label: 'GPU utilization', value: 'Share of time any work was running' },
      { label: 'SM activity', value: 'Share of SMs that were busy' },
    ],
    related: ['control-tower', 'nvidia-smi', 'partitioned-hall', 'sm', 'memory-vs-compute-bound'],
    shareSim: { sharing: 'one' },
  },
  {
    id: 'workload-management',
    zone,
    kind: 'concept',
    name: 'Workload management',
    aliases: ['scheduling', 'resource management'],
    category: 'Scheduling',
    metaphor: 'Deciding which job gets which machines, and when',
    summary:
      'Workload management is everything that decides who uses the GPUs: queueing jobs, setting priorities and quotas, placing each job on machines that fit it, and sharing a GPU when one job cannot fill it. Slurm and Kubernetes are the two common tools, and GPU sharing is how a single GPU is divided.',
    facts: [{ label: 'Covers', value: 'Queues, priorities, placement and GPU sharing' }],
    related: ['dispatcher-desk', 'container-yard', 'partitioned-hall', 'cluster-manager'],
  },
  {
    id: 'mlops',
    zone,
    kind: 'concept',
    name: 'MLOps',
    aliases: ['machine learning operations'],
    category: 'Operations',
    metaphor: 'Running the whole factory as a routine: build, ship, watch, repeat',
    summary:
      'MLOps is the set of habits and tools for taking a model from experiment to a service people rely on: versioned data and code, repeatable training, tested releases, deployment, and monitoring that feeds back into the next version. It is operations work applied to models.',
    facts: [{ label: 'Covers', value: 'Training, release, deployment and monitoring of models' }],
    related: ['container-yard', 'control-tower', 'shipping-dock', 'ai-enterprise'],
  },
];
