import type { Item } from '../types';

const zone = 'gpu-hall' as const;

// All numbers below come from SPEC §8. Anything else is marked TODO(fact) with a visible placeholder.
export const gpuHallItems: Item[] = [
  {
    id: 'data',
    zone,
    kind: 'object',
    number: 1,
    name: 'Data',
    category: 'Input',
    metaphor: 'Parcels arriving on the road',
    swatch: 'scene-parcel',
    summary:
      'Data is the cargo of the factory: training examples, prompts and model weights, all packed into parcels. Parcels only help once they reach a worker, so how fast they arrive matters as much as how many workers there are.',
    facts: [{ label: 'Size of one value', value: 'FP32 4 B · FP16/BF16 2 B · FP8/INT8 1 B' }],
    related: ['memory-bandwidth', 'hbm', 'cpu', 'fp8'],
    anchorId: 'data',
  },
  {
    id: 'cpu',
    zone,
    kind: 'object',
    number: 2,
    name: 'CPU',
    category: 'Compute',
    metaphor: "The manager's office",
    swatch: 'scene-roof',
    summary:
      'The CPU coordinates the work: it prepares data, hands jobs to the GPU and handles everything that is not bulk arithmetic. It is built for varied, step-by-step decisions, not for doing the same sum millions of times at once.',
    facts: [{ label: 'Typical core count', value: 'TODO(fact): add a verified CPU core count' }],
    compare: {
      with: ['GPU'],
      fullCompareId: 'cpu-vs-gpu',
      rows: [
        { label: 'In the factory', values: ["The manager's office", 'The production hall'] },
        { label: 'Good at', values: ['Varied, sequential decisions', 'One operation on huge amounts of data'], best: 0 },
        { label: 'Cores', values: ['Few, strong', 'Many, simple'] },
        { label: 'Role in AI', values: ['Coordinates and feeds', 'Does the bulk maths'] },
      ],
    },
    related: ['gpu', 'cpu-vs-gpu', 'data'],
    anchorId: 'cpu',
  },
  {
    id: 'gpu',
    zone,
    kind: 'object',
    number: 3,
    name: 'GPU',
    category: 'Compute',
    metaphor: 'The production hall',
    swatch: 'scene-hall',
    summary:
      'A GPU is a hall full of small workshops that all do the same kind of work at once. Instead of a few clever workers it has an enormous crowd, which suits AI: training and inference are mostly the same multiplication repeated across huge tables of numbers.',
    facts: [
      { label: 'H100 SXM SMs', value: '132' },
      { label: 'CUDA cores per SM', value: '128 (FP32)' },
      { label: 'Tensor Cores per SM', value: '4 (4th generation)' },
      { label: 'H100 SXM memory', value: '80 GB HBM3 · ~3.35 TB/s' },
    ],
    compare: {
      with: ['CPU'],
      fullCompareId: 'cpu-vs-gpu',
      rows: [
        { label: 'In the factory', values: ['The production hall', "The manager's office"] },
        { label: 'Good at', values: ['One operation on huge amounts of data', 'Varied, sequential decisions'], best: 0 },
        { label: 'Cores', values: ['Many, simple', 'Few, strong'] },
        { label: 'Role in AI', values: ['Does the bulk maths', 'Coordinates and feeds'] },
      ],
    },
    related: ['sm', 'cpu', 'hbm', 'cpu-vs-gpu'],
    anchorId: 'gpu',
  },
  {
    id: 'sm',
    zone,
    kind: 'object',
    number: 4,
    name: 'SM',
    category: 'GPU part',
    metaphor: 'A workshop cell inside the hall',
    swatch: 'scene-hall',
    summary:
      'A Streaming Multiprocessor (SM) is one workshop cell of the GPU hall. Each cell has its own workers and stamping presses, and the hall is simply many identical cells working in parallel. How many cells are busy tells you how much of the hall is actually working. The scene draws only a few cells to keep it readable.',
    facts: [
      { label: 'H100 SXM', value: '132 SMs' },
      { label: 'CUDA cores per SM', value: '128 (FP32)' },
      { label: 'Tensor Cores per SM', value: '4 (4th generation)' },
      { label: 'Threads per warp', value: '32' },
    ],
    related: ['cuda-core', 'tensor-core', 'gpu', 'memory-vs-compute-bound'],
    anchorId: 'sm',
  },
  {
    id: 'cuda-core',
    zone,
    kind: 'object',
    number: 5,
    name: 'CUDA core',
    category: 'GPU part',
    metaphor: 'A worker',
    swatch: 'scene-hall',
    summary:
      'A CUDA core is one worker in a cell: it does a single small piece of arithmetic at a time. Workers are busy only when data arrives on time. When the conveyor cannot keep up, they stand grey and idle, which you can see in the scene with the Simulate bar.',
    facts: [
      { label: 'Per H100 SM', value: '128 (FP32)' },
      { label: 'Threads per warp', value: '32' },
    ],
    related: ['sm', 'tensor-core', 'memory-bandwidth', 'memory-vs-compute-bound'],
    anchorId: 'cuda-core',
  },
  {
    id: 'tensor-core',
    zone,
    kind: 'object',
    number: 6,
    name: 'Tensor Core',
    category: 'GPU part',
    metaphor: 'A stamping press that handles a whole tray',
    swatch: 'scene-roof',
    summary:
      'A Tensor Core is a specialised press: where a worker handles one pair of numbers, the press stamps a whole small tray of multiply-and-add work in one go. Matrix multiplication, the heart of AI, fits it almost perfectly, which is why new number formats arrive on Tensor Cores first.',
    facts: [
      { label: 'Per H100 SM', value: '4 (4th generation)' },
      {
        label: 'Firsts',
        value: 'Volta FP16 · Turing INT8/INT4 · Ampere TF32, BF16, structured sparsity, MIG · Hopper FP8 + Transformer Engine · Blackwell FP4',
      },
    ],
    compare: {
      with: ['CUDA core'],
      rows: [
        { label: 'In the factory', values: ['A stamping press', 'A worker'] },
        { label: 'Handles', values: ['A whole tray at once', 'One small piece at a time'], best: 0 },
        { label: 'Best for', values: ['Matrix multiplication', 'General arithmetic'] },
      ],
    },
    related: ['cuda-core', 'sm', 'fp8'],
    anchorId: 'tensor-core',
  },
  {
    id: 'hbm',
    zone,
    kind: 'object',
    number: 7,
    name: 'HBM',
    category: 'Memory',
    metaphor: 'The warehouse next to the GPU hall',
    swatch: 'scene-storage',
    summary:
      "High Bandwidth Memory is the GPU's main memory: stacked DRAM placed right beside the chip. Capacity sets how large a model fits on one GPU; bandwidth sets how fast data reaches the cores. For LLM inference, HBM bandwidth is usually the bottleneck, not compute.",
    facts: [
      { label: 'H100 SXM', value: '80 GB HBM3 · ~3.35 TB/s' },
      { label: 'H200', value: '141 GB HBM3e · ~4.8 TB/s' },
      { label: 'Hierarchy', value: 'Registers → L1 → L2 (50 MB) → HBM' },
    ],
    compare: {
      with: ['GDDR'],
      fullCompareId: 'hbm-vs-gddr',
      rows: [
        { label: 'Placement', values: ['Stacked beside the chip', 'Spread on the board'] },
        { label: 'Bandwidth', values: ['Very high', 'Lower'], best: 0 },
        { label: 'Cost', values: ['Higher', 'Lower'] },
        { label: 'Found in', values: ['Data center GPUs', 'Gaming GPUs'] },
      ],
    },
    related: ['memory-bandwidth', 'memory-vs-compute-bound', 'fp8', 'gpudirect-storage'],
    anchorId: 'hbm',
  },
  {
    id: 'memory-bandwidth',
    zone,
    kind: 'object',
    number: 8,
    name: 'Memory bandwidth',
    category: 'Memory',
    metaphor: 'The conveyor from warehouse to hall',
    swatch: 'scene-path',
    summary:
      'Memory bandwidth is the speed of the conveyor between the HBM warehouse and the hall: how much cargo can arrive each second. When it is slower than the workers need, the cores wait and the parcels turn coral in the scene. Smaller crates (fewer bytes per value) put more values on the same belt.',
    facts: [
      { label: 'H100 SXM', value: '~3.35 TB/s' },
      { label: 'H200', value: '~4.8 TB/s' },
      { label: 'Crate size', value: 'FP16 2 B vs FP8 1 B per value' },
    ],
    related: ['hbm', 'memory-vs-compute-bound', 'data', 'fp8'],
    anchorId: 'memory-bandwidth',
    sim: { workload: 'inference' },
  },
  {
    id: 'cpu-vs-gpu',
    zone,
    kind: 'concept',
    name: 'CPU vs GPU',
    category: 'Comparison',
    metaphor: "A manager's office next to a production hall",
    swatch: 'scene-roof',
    summary:
      'The CPU decides and coordinates; the GPU does the bulk of the repetitive arithmetic. They are partners, not rivals: the GPU is only as useful as the CPU and the data path that keep it fed.',
    facts: [{ label: 'H100 SXM', value: '132 SMs, 128 CUDA cores each' }],
    compare: {
      with: ['GPU'],
      fullCompareId: 'cpu-vs-gpu',
      rows: [
        { label: 'In the factory', values: ["The manager's office", 'The production hall'] },
        { label: 'Good at', values: ['Varied, sequential decisions', 'One operation on huge amounts of data'], best: 1 },
        { label: 'Cores', values: ['Few, strong', 'Many, simple'] },
        { label: 'Role in AI', values: ['Coordinates and feeds', 'Does the bulk maths'] },
      ],
    },
    related: ['cpu', 'gpu', 'sm'],
  },
  {
    id: 'memory-vs-compute-bound',
    zone,
    kind: 'concept',
    name: 'Memory- vs compute-bound',
    category: 'Concept',
    metaphor: 'Is the conveyor or the hall the limit?',
    swatch: 'scene-parcel-hot',
    summary:
      'A job is memory-bound when the workers wait for data, and compute-bound when the data waits for workers. LLM inference is usually memory-bound; training usually keeps the hall busy. Use the Simulate bar to flip between them and watch the workers go grey.',
    facts: [{ label: 'Simulate bar', value: 'Illustrative, not measured' }],
    compare: {
      with: ['Compute-bound'],
      rows: [
        { label: 'In the factory', values: ['Conveyor too slow, workers wait', 'Workers all busy, parcels wait'] },
        { label: 'Typical job', values: ['LLM inference', 'Training'] },
        { label: 'Helps', values: ['More bandwidth, smaller crates', 'More compute'] },
      ],
    },
    related: ['memory-bandwidth', 'hbm', 'sm', 'training-vs-inference', 'fp8'],
    sim: { workload: 'inference' },
  },
  {
    id: 'training-vs-inference',
    zone,
    kind: 'concept',
    name: 'Training vs inference',
    category: 'Workload',
    metaphor: 'A production line being built vs a 24/7 shop',
    swatch: 'scene-hall',
    summary:
      'Training builds the production line: many workers, a long time, the hall kept busy. Inference runs the shop: a queue of customers, each served fast. They stress the factory differently, so the same GPU can be limited by compute in one and by memory in the other.',
    facts: [{ label: 'Simulate bar', value: 'Illustrative, not measured' }],
    compare: {
      with: ['Inference'],
      fullCompareId: 'training-vs-inference',
      rows: [
        { label: 'In the factory', values: ['Building the production line', 'Running the 24/7 shop'] },
        { label: 'Goal', values: ['Learn the weights', 'Answer requests quickly'] },
        { label: 'Usually limited by', values: ['Compute', 'Memory bandwidth'] },
        { label: 'Runs', values: ['Long jobs', 'Always on'] },
      ],
    },
    related: ['memory-vs-compute-bound', 'gpu', 'memory-bandwidth'],
  },
];
