import type { Item } from '../types';

const zone = 'packing-station' as const;

// All numbers below come from SPEC §8. Anything else is marked TODO(fact) with a visible placeholder.
export const packingStationItems: Item[] = [
  {
    id: 'fp32',
    zone,
    kind: 'object',
    number: 1,
    name: 'FP32',
    aliases: ['single precision', 'float32'],
    category: 'Number format',
    metaphor: 'The biggest crate on the dock',
    swatch: 'scene-storage',
    summary:
      'FP32 stores each number in 4 bytes, with 8 exponent bits for range and 23 mantissa bits for precision. It is the careful, wide format: plenty of range and detail, but every crate is the largest on the dock, so fewer numbers fit in memory and on each truck.',
    facts: [
      { label: 'Size', value: '4 B per number' },
      { label: 'Bits', value: '8 exponent · 23 mantissa' },
    ],
    related: ['bf16-fp16', 'tf32', 'delivery-truck', 'mixed-precision'],
    anchorId: 'fp32',
    packSim: { format: 'fp32' },
  },
  {
    id: 'bf16-fp16',
    zone,
    kind: 'object',
    number: 2,
    name: 'BF16 / FP16',
    aliases: ['BF16', 'FP16', 'bfloat16', 'half precision'],
    category: 'Number format',
    metaphor: 'The medium crate, in two layouts',
    swatch: 'scene-parcel',
    summary:
      'Both take 2 bytes per number, half the FP32 crate. FP16 spends its bits on precision (5 exponent, 10 mantissa). BF16 spends them on range (8 exponent, 7 mantissa), the same range as FP32, which copes better with the wide swings in training values.',
    facts: [
      { label: 'Size', value: '2 B per number' },
      { label: 'FP16 bits', value: '5 exponent · 10 mantissa' },
      { label: 'BF16 bits', value: '8 exponent · 7 mantissa' },
      { label: 'On Tensor Cores', value: 'FP16 since Volta · BF16 since Ampere' },
    ],
    related: ['fp32', 'fp8', 'tf32', 'mixed-precision'],
    anchorId: 'bf16-fp16',
    packSim: { format: 'bf16' },
  },
  {
    id: 'fp8',
    zone,
    kind: 'object',
    number: 3,
    name: 'FP8',
    aliases: ['float8', 'E4M3', 'E5M2'],
    category: 'Number format',
    metaphor: 'A small box with its own two layouts',
    swatch: 'scene-hall',
    summary:
      'FP8 stores each number in 1 byte, in one of two layouts, E4M3 or E5M2. Half the size of BF16 means twice as many numbers per crate and per truck. It has little room for range and detail, so the Transformer Engine decides where it is safe to use.',
    facts: [
      { label: 'Size', value: '1 B per number' },
      { label: 'Layouts', value: 'E4M3 or E5M2' },
      { label: 'On Tensor Cores', value: 'Hopper, with the Transformer Engine' },
    ],
    compare: {
      with: ['BF16'],
      fullCompareId: 'fp-formats',
      rows: [
        { label: 'In the factory', values: ['A small box', 'The medium crate'] },
        { label: 'Size', values: ['1 B per number', '2 B per number'], best: 0 },
        { label: 'Layout', values: ['E4M3 or E5M2', '8 exponent · 7 mantissa'] },
        { label: 'Arrived with', values: ['Hopper', 'Ampere'] },
      ],
    },
    related: ['bf16-fp16', 'transformer-engine', 'quantization', 'hbm', 'delivery-truck'],
    anchorId: 'fp8',
    packSim: { format: 'fp8' },
  },
  {
    id: 'int8',
    zone,
    kind: 'object',
    number: 4,
    name: 'INT8',
    aliases: ['integer 8'],
    category: 'Number format',
    metaphor: 'The other small box: whole numbers only',
    swatch: 'scene-network',
    summary:
      'INT8 stores whole numbers in 1 byte, the same size as FP8 but a different kind of box: no exponent, just integers. Trained models are usually converted into it afterwards, mostly to run inference with less memory.',
    facts: [
      { label: 'Size', value: '1 B per number' },
      { label: 'On Tensor Cores', value: 'Since Turing' },
    ],
    related: ['fp8', 'quantization', 'delivery-truck'],
    anchorId: 'int8',
    packSim: { format: 'int8' },
  },
  {
    id: 'delivery-truck',
    zone,
    kind: 'object',
    number: 5,
    name: 'Delivery truck',
    aliases: ['memory', 'bandwidth'],
    category: 'Memory',
    metaphor: 'The truck that carries crates to the hall',
    swatch: 'scene-path',
    summary:
      'The truck stands for the memory and the path that carry numbers to the hall. A truck holds a fixed amount, so smaller crates mean more numbers per trip: a smaller format cuts both how much memory the weights need and how much data has to move.',
    facts: [
      { label: 'Size per number', value: 'FP32 4 B · FP16/BF16 2 B · FP8/INT8 1 B' },
      { label: 'One H100 SXM', value: '80 GB HBM3' },
    ],
    related: ['fp32', 'fp8', 'hbm', 'memory-bandwidth'],
    anchorId: 'delivery-truck',
  },
  {
    id: 'transformer-engine',
    zone,
    kind: 'object',
    number: 6,
    name: 'Transformer Engine',
    aliases: ['TE'],
    category: 'Hardware and software',
    metaphor: 'The packer who picks a crate size for each layer',
    swatch: 'scene-roof',
    summary:
      'Introduced with Hopper, the Transformer Engine chooses the number format layer by layer: FP8 where it is safe, a wider format where it is not. You keep most of the small box savings without packing every layer the same way.',
    facts: [{ label: 'Introduced with', value: 'Hopper, together with FP8' }],
    related: ['fp8', 'mixed-precision', 'bf16-fp16'],
    anchorId: 'transformer-engine',
    packSim: { format: 'fp8' },
  },
  {
    id: 'tf32',
    zone,
    kind: 'concept',
    name: 'TF32',
    aliases: ['TensorFloat-32'],
    category: 'Number format',
    metaphor: 'An FP32 crate with a leaner label',
    summary:
      'TF32 keeps the 8 exponent bits of FP32, so it has the same range, but only 10 mantissa bits, the same precision as FP16. Tensor Cores gained it with Ampere so that FP32 maths can run faster without changing the code that uses it.',
    facts: [
      { label: 'Bits', value: '8 exponent · 10 mantissa' },
      { label: 'On Tensor Cores', value: 'Since Ampere' },
    ],
    related: ['fp32', 'bf16-fp16'],
  },
  {
    id: 'mixed-precision',
    zone,
    kind: 'concept',
    name: 'Mixed precision',
    category: 'Technique',
    metaphor: 'Different crate sizes on the same truck',
    summary:
      'Mixed precision uses small formats for most of the arithmetic and keeps a wider one where accuracy needs it, such as when adding up many small values. The result is close to full-width accuracy at much lower memory and bandwidth cost.',
    facts: [],
    related: ['transformer-engine', 'fp32', 'bf16-fp16', 'fp8'],
  },
  {
    id: 'quantization',
    zone,
    kind: 'concept',
    name: 'Quantization',
    aliases: ['quantisation'],
    category: 'Technique',
    metaphor: 'Repacking a finished order into smaller boxes',
    summary:
      'Quantization converts a trained model to a smaller format, such as INT8 or FP8, so it needs less memory and moves faster. It is a trade: each number holds less detail, so the converted model has to be checked against the original.',
    facts: [],
    related: ['int8', 'fp8', 'mixed-precision'],
  },
];
