import type { Item } from '../types';

const zone = 'production-line' as const;

// No numbers are needed in this zone, so every fact below is a description. Anything beyond SPEC §8 is general, not measured.
export const productionLineItems: Item[] = [
  {
    id: 'ngc',
    zone,
    kind: 'object',
    number: 1,
    name: 'NGC',
    aliases: ['NVIDIA NGC', 'NGC catalog'],
    category: 'Software',
    metaphor: 'The tool store',
    swatch: 'scene-network',
    summary:
      'NGC is a catalog of ready-to-run GPU software: containers, pretrained models and tools that have already been tested and tuned. A team starts from parts that work together instead of assembling and tuning every tool by hand.',
    facts: [{ label: 'Holds', value: 'Containers, pretrained models and tools' }],
    related: ['rapids', 'training-line', 'ai-enterprise', 'cuda-x'],
    anchorId: 'ngc',
    lineSim: { need: 'tools' },
  },
  {
    id: 'rapids',
    zone,
    kind: 'object',
    number: 2,
    name: 'RAPIDS',
    aliases: ['cuDF', 'GPU data science'],
    category: 'Software',
    metaphor: 'The prep area',
    swatch: 'scene-hall',
    summary:
      'RAPIDS runs data preparation and classic machine learning on the GPU, through interfaces that look like the familiar Python tools. Sorting and cleaning the raw parcels is often the slowest part of the job, so doing it on the same fast machines keeps the line from waiting.',
    facts: [{ label: 'Does', value: 'Data preparation and machine learning on the GPU' }],
    related: ['ngc', 'training-line', 'cuda-x'],
    anchorId: 'rapids',
    lineSim: { need: 'prepare' },
  },
  {
    id: 'training-line',
    zone,
    kind: 'object',
    number: 3,
    name: 'Training line',
    aliases: ['training'],
    category: 'Workload',
    metaphor: 'The production line being built: many workers, a long time',
    swatch: 'scene-hall',
    summary:
      'Training builds the model: many GPUs work together for a long time, passing results to each other after every step so they stay in agreement. It is the heavy, one-off construction of the line, and it usually keeps the machines busy with compute.',
    facts: [{ label: 'Typically', value: 'Many GPUs, long jobs, compute-bound' }],
    compare: {
      with: ['Inference'],
      rows: [
        { label: 'In the factory', values: ['Building the production line', 'Running the 24/7 shop'] },
        { label: 'Goal', values: ['Learn the weights', 'Answer requests quickly'] },
        { label: 'Runs', values: ['Long jobs', 'Always on'] },
      ],
      fullCompareId: 'training-vs-inference',
    },
    related: ['nccl', 'training-vs-inference', 'inference-shop', 'checkpoint', 'rapids'],
    anchorId: 'training-line',
    lineSim: { need: 'train' },
  },
  {
    id: 'tensorrt',
    zone,
    kind: 'object',
    number: 4,
    name: 'TensorRT',
    aliases: ['TensorRT-LLM'],
    category: 'Software',
    metaphor: 'The compactor',
    swatch: 'scene-network',
    summary:
      'TensorRT takes a trained model and compiles it into a leaner, faster version for serving: it merges steps and can use smaller number formats. The model that comes out of the press does the same job in a smaller package, which is what the shop needs.',
    facts: [{ label: 'Does', value: 'Optimises a trained model for inference' }],
    related: ['shipping-dock', 'quantization', 'fp8', 'inference-shop'],
    anchorId: 'tensorrt',
    lineSim: { need: 'optimize' },
  },
  {
    id: 'shipping-dock',
    zone,
    kind: 'object',
    number: 5,
    name: 'Shipping dock',
    aliases: ['Triton', 'NIM', 'Triton Inference Server', 'NVIDIA NIM'],
    category: 'Software',
    metaphor: 'A dock with two bays: a configurable one and a pre-packed box',
    swatch: 'scene-storage',
    summary:
      'The dock is where finished models leave the line to serve requests. Triton is the configurable bay: you choose models, frameworks and settings yourself. NIM is the pre-packed box: a model already optimised and wrapped with an interface, ready to run.',
    facts: [{ label: 'Two ways to ship', value: 'Triton (configurable) or NIM (pre-packed)' }],
    compare: {
      with: ['NIM'],
      rows: [
        { label: 'In the factory', values: ['Configurable shipping dock', 'Pre-packed box'] },
        { label: 'You get', values: ['Control over setup', 'A ready-made endpoint'] },
        { label: 'Best when', values: ['You need a custom mix', 'You want to start fast'] },
      ],
      fullCompareId: 'triton-vs-nim',
    },
    related: ['tensorrt', 'inference-shop', 'ai-enterprise', 'customer-queue'],
    anchorId: 'shipping-dock',
    lineSim: { need: 'serve-custom' },
  },
  {
    id: 'inference-shop',
    zone,
    kind: 'object',
    number: 6,
    name: '24/7 shop',
    aliases: ['inference', 'serving', 'model serving'],
    category: 'Workload',
    metaphor: 'The 24/7 shop',
    swatch: 'scene-roof',
    summary:
      'Inference is the finished model at work: it is always on, answering requests as they come. Unlike training it does not change the model, and it tends to wait on memory bandwidth rather than compute, so keeping data close to the cores matters most.',
    facts: [{ label: 'Typically', value: 'Always on, memory-bandwidth-bound' }],
    related: ['training-vs-inference', 'customer-queue', 'shipping-dock', 'memory-bandwidth', 'tensorrt'],
    anchorId: 'inference-shop',
  },
  {
    id: 'customer-queue',
    zone,
    kind: 'object',
    number: 7,
    name: 'Customer queue',
    aliases: ['requests', 'latency', 'throughput'],
    category: 'Workload',
    metaphor: 'A queue of customers, each served fast',
    swatch: 'scene-idle',
    summary:
      'Requests arrive one after another, and each customer wants an answer quickly. The shop has to keep every individual wait short while still serving many at once, so serving is judged on how fast each request is answered as well as on how many it handles in total.',
    facts: [{ label: 'Measured by', value: 'Latency per request and total throughput' }],
    related: ['inference-shop', 'shipping-dock', 'training-vs-inference'],
    anchorId: 'customer-queue',
  },
  {
    id: 'cuda-x',
    zone,
    kind: 'concept',
    name: 'CUDA and CUDA-X',
    aliases: ['CUDA', 'CUDA-X libraries'],
    category: 'Software',
    metaphor: 'The language of the factory floor, and the libraries built on it',
    summary:
      'CUDA is the platform that lets programs run on the GPU. CUDA-X is the collection of libraries built on it, for maths, deep learning, data processing and more, so most teams call a tuned library instead of writing GPU code themselves.',
    facts: [{ label: 'Relationship', value: 'CUDA-X libraries are built on CUDA' }],
    related: ['rapids', 'ngc', 'nccl', 'gpu'],
  },
  {
    id: 'nccl',
    zone,
    kind: 'concept',
    name: 'NCCL',
    aliases: ['collective communications'],
    category: 'Software',
    metaphor: 'The foreman who gets every worker to swap results efficiently',
    summary:
      'NCCL is the library GPUs use to exchange data with each other during training: sharing results, adding them up and sending the totals back. It picks routes that make the most of NVLink inside a machine and the network between machines.',
    facts: [{ label: 'Used for', value: 'GPU-to-GPU communication in multi-GPU training' }],
    related: ['training-line', 'nvlink-bridge', 'infiniband', 'nvswitch-hub'],
  },
  {
    id: 'ai-enterprise',
    zone,
    kind: 'concept',
    name: 'NVIDIA AI Enterprise',
    aliases: ['AI Enterprise'],
    category: 'Software',
    metaphor: 'The service contract for the whole line',
    summary:
      'AI Enterprise is the supported, production-grade version of the software stack: tested containers, frameworks and tools such as Triton and NIM, with security updates and support behind them. It is what a company buys when the line must keep running.',
    facts: [{ label: 'Adds', value: 'Support, security updates and tested releases' }],
    related: ['ngc', 'shipping-dock', 'training-line'],
  },
];
