import type { Item } from '../types';

const zone = 'storage-yard' as const;

// All numbers below come from SPEC §8. Anything else is marked TODO(fact) with a visible placeholder.
export const storageYardItems: Item[] = [
  {
    id: 'gpu-hall',
    zone,
    kind: 'object',
    number: 1,
    name: 'GPU hall',
    aliases: ['GPU', 'H100'],
    category: 'Compute',
    metaphor: 'The production hall that everything in the yard exists to feed',
    swatch: 'scene-hall',
    summary:
      'Every road and shed in the storage yard has one job: keep this hall supplied. However fast the machines inside are, they sit idle whenever parcels arrive late, so the speed of the path from storage to GPU memory decides how busy the hall stays.',
    facts: [{ label: 'Memory per H100 SXM', value: '80 GB HBM3' }],
    related: ['nvme-cache-shed', 'gpudirect-storage', 'parallel-file-system', 'gpu', 'hbm'],
    anchorId: 'gpu-hall',
  },
  {
    id: 'nvme-cache-shed',
    zone,
    kind: 'object',
    number: 2,
    name: 'NVMe cache shed',
    aliases: ['local NVMe cache', 'NVMe', 'cache', 'local cache'],
    category: 'Storage',
    metaphor: 'A shed right next to the building',
    swatch: 'scene-storage',
    summary:
      'Fast flash drives beside the GPUs keep a copy of data that has already been read, so the next epoch does not go back to the far warehouse. The shed is small, so it holds only part of the data, but what it holds arrives fastest. The best AI storage is the one with the best read and re-read performance.',
    facts: [{ label: 'What matters', value: 'Read and re-read performance' }],
    compare: {
      with: ['Parallel file system', 'Object storage'],
      rows: [
        { label: 'In the factory', values: ['Shed next to the building', 'Big warehouse', 'Remote depot at the port'] },
        { label: 'Speed', values: ['Fastest', 'Fast', 'Slowest'], best: 0 },
        { label: 'Capacity', values: ['Smallest', 'Large', 'Largest'], best: 2 },
      ],
      fullCompareId: 'storage-tiers',
    },
    related: ['read-and-reread', 'epoch', 'parallel-file-system', 'object-storage-depot', 'gpu-hall'],
    anchorId: 'nvme-cache-shed',
    storageSim: { cache: true, epoch: 2 },
  },
  {
    id: 'parallel-file-system',
    zone,
    kind: 'object',
    number: 3,
    name: 'Parallel file system',
    aliases: ['parallel FS', 'shared file system'],
    category: 'Storage',
    metaphor: 'A big warehouse with many loading doors',
    swatch: 'scene-storage',
    summary:
      'Many storage servers present one shared file system, and each read is spread across them so many GPUs can load data at the same moment. It is the main store a training job reads from, shared by the whole cluster rather than tied to one machine.',
    facts: [{ label: 'Reached over', value: 'The storage network' }],
    compare: {
      with: ['NVMe cache', 'Object storage'],
      rows: [
        { label: 'In the factory', values: ['Big warehouse', 'Shed next to the building', 'Remote depot at the port'] },
        { label: 'Speed', values: ['Fast', 'Fastest', 'Slowest'] },
        { label: 'Capacity', values: ['Large', 'Smallest', 'Largest'] },
      ],
      fullCompareId: 'storage-tiers',
    },
    related: ['nvme-cache-shed', 'object-storage-depot', 'storage-fabric', 'checkpoint'],
    anchorId: 'parallel-file-system',
    storageSim: { cache: false },
  },
  {
    id: 'object-storage-depot',
    zone,
    kind: 'object',
    number: 4,
    name: 'Object storage depot',
    aliases: ['object storage', 'data lake'],
    category: 'Storage',
    metaphor: 'A remote depot at the port: far away, cheaper, slower',
    swatch: 'scene-storage',
    summary:
      'Object storage keeps enormous amounts of data cheaply and safely, fetched by name over the network instead of read as files. It is too far and too slow to train from directly, so data is staged into the faster warehouse and shed before the job starts.',
    facts: [{ label: 'Best for', value: 'Keeping everything, cheaply' }],
    compare: {
      with: ['NVMe cache', 'Parallel file system'],
      rows: [
        { label: 'In the factory', values: ['Remote depot at the port', 'Shed next to the building', 'Big warehouse'] },
        { label: 'Speed', values: ['Slowest', 'Fastest', 'Fast'] },
        { label: 'Capacity', values: ['Largest', 'Smallest', 'Large'], best: 0 },
      ],
      fullCompareId: 'storage-tiers',
    },
    related: ['parallel-file-system', 'nvme-cache-shed', 'checkpoint'],
    anchorId: 'object-storage-depot',
  },
  {
    id: 'gpudirect-storage',
    zone,
    kind: 'object',
    number: 5,
    name: 'GPUDirect Storage',
    aliases: ['GDS', 'GPU Direct Storage'],
    category: 'Storage',
    metaphor: 'A courier delivering straight into the hall',
    swatch: 'scene-coolant',
    summary:
      'Normally every parcel from storage is unpacked in the CPU\'s office and repacked before it reaches the GPU. GPUDirect Storage opens a direct lane so data goes from storage into GPU memory without that stop, which saves time and leaves the CPU free for other work.',
    facts: [{ label: 'Path', value: 'Storage ↔ GPU memory, bypassing CPU memory' }],
    compare: {
      with: ['GPUDirect RDMA'],
      rows: [
        { label: 'In the factory', values: ['Courier from the warehouse into the hall', 'Courier from another town into the hall'] },
        { label: 'Moves data between', values: ['Storage and GPU memory', 'Network card and GPU memory'] },
        { label: 'Lives in', values: ['The storage yard', 'The transport network'] },
      ],
      fullCompareId: 'gpudirect-rdma-vs-storage',
    },
    related: ['gpudirect-rdma', 'gpu-hall', 'parallel-file-system', 'cpu'],
    anchorId: 'gpudirect-storage',
    storageSim: { path: 'gpudirect' },
  },
  {
    id: 'checkpoint',
    zone,
    kind: 'object',
    number: 6,
    name: 'Checkpoint',
    aliases: ['checkpointing', 'snapshot'],
    category: 'Training',
    metaphor: 'A snapshot of the production line',
    swatch: 'scene-coolant',
    summary:
      'Every so often a training job saves its whole state, a copy of the production line, back to the warehouse. If a machine fails, the job restarts from the last snapshot instead of from the beginning. The copy is one big burst of writes, so storage has to absorb it quickly.',
    facts: [{ label: 'Direction', value: 'GPU hall → warehouse (a write, not a read)' }],
    related: ['parallel-file-system', 'object-storage-depot', 'gpu-hall', 'epoch'],
    anchorId: 'checkpoint',
  },
  {
    id: 'read-and-reread',
    zone,
    kind: 'concept',
    name: 'Read and re-read',
    aliases: ['re-read', 'reread'],
    category: 'Training',
    metaphor: 'Walking the same aisle again every lap',
    summary:
      'Training reads the same dataset over and over, once per epoch. So speed on the first read is not enough: re-read performance counts just as much, and it is exactly what a local cache improves. The best AI storage is the one with the best read and re-read performance.',
    facts: [{ label: 'Rule of thumb', value: 'Best AI storage = best read and re-read performance' }],
    related: ['epoch', 'nvme-cache-shed', 'parallel-file-system'],
    storageSim: { cache: true, epoch: 3 },
  },
  {
    id: 'epoch',
    zone,
    kind: 'concept',
    name: 'Epoch',
    category: 'Training',
    metaphor: 'One full lap through the warehouse',
    summary:
      'An epoch is one complete pass over the training data. A job runs many of them. The first lap has to fetch everything from the warehouse; later laps can reuse what the cache shed kept, which is why the second epoch is usually faster.',
    facts: [{ label: 'Per epoch', value: 'Every example is read once' }],
    related: ['read-and-reread', 'nvme-cache-shed', 'checkpoint'],
    storageSim: { epoch: 2 },
  },
  {
    id: 'storage-fabric',
    zone,
    kind: 'concept',
    name: 'Storage fabric',
    aliases: ['storage network'],
    category: 'Network',
    metaphor: 'A dedicated road to the warehouses',
    summary:
      'The storage fabric is the separate network that carries storage traffic, one of the four cluster networks. Keeping it apart means a big data load cannot get in the way of the GPUs talking to each other.',
    facts: [{ label: 'One of', value: 'The four cluster networks' }],
    related: ['four-cluster-networks', 'parallel-file-system', 'infiniband'],
  },
];
