import type { Item } from '../types';

const zone = 'transport-network' as const;

// All numbers below come from SPEC §8. Anything else is marked TODO(fact) with a visible placeholder.
export const transportNetworkItems: Item[] = [
  {
    id: 'dgx-node',
    zone,
    kind: 'object',
    number: 1,
    name: 'DGX node',
    aliases: ['node', 'server', 'ConnectX-7'],
    category: 'Hardware',
    metaphor: 'A depot with its own loading docks',
    swatch: 'scene-wall',
    summary:
      'In a cluster, each DGX is one node. Inside it the GPUs talk over NVLink, but to reach another node data has to leave through the network cards, the loading docks on the front. A cluster is only as fast as its docks and the roads and rails they open onto.',
    facts: [
      { label: 'Network adapter', value: 'ConnectX-7, up to 400 Gb/s' },
      { label: 'In a DGX H100', value: '8× H100 GPUs' },
    ],
    related: ['dpu-gatehouse', 'infiniband', 'ethernet-road', 'dgx-system', 'scale-up-vs-scale-out'],
    anchorId: 'dgx-node',
  },
  {
    id: 'dpu-gatehouse',
    zone,
    kind: 'object',
    number: 2,
    name: 'DPU gatehouse',
    aliases: ['DPU', 'BlueField', 'data processing unit'],
    category: 'Hardware',
    metaphor: 'A checkpoint that inspects and routes traffic so the factory floor does not have to',
    swatch: 'scene-network',
    summary:
      'A DPU is a processor that sits in the path of the network and takes over the chores around it: moving packets, enforcing security rules and handling storage traffic. The CPU and GPUs stay on the production line while the gatehouse checks every parcel in and out.',
    facts: [{ label: 'Role', value: 'Offloads networking, storage and security work from the CPU' }],
    related: ['dgx-node', 'rdma', 'gpudirect-rdma', 'spectrum-x-control'],
    anchorId: 'dpu-gatehouse',
  },
  {
    id: 'infiniband',
    zone,
    kind: 'object',
    number: 3,
    name: 'InfiniBand rail',
    aliases: ['InfiniBand', 'IB'],
    category: 'Network',
    metaphor: 'A private freight rail that never drops cargo',
    swatch: 'scene-network',
    summary:
      'InfiniBand is a network built for clusters. It is lossless: a sender only moves cargo when the next station has room for it, so nothing falls off, and delays stay small and steady. The price is a dedicated fabric instead of the shared roads the rest of the world uses.',
    facts: [{ label: 'ConnectX-7', value: 'up to 400 Gb/s' }],
    compare: {
      with: ['Ethernet', 'Spectrum-X'],
      rows: [
        { label: 'In the factory', values: ['Private freight rail', 'Public road', 'Road with smart traffic control'] },
        { label: 'When crowded', values: ['Waits, never drops', 'Drops parcels and re-sends', 'Steers round the jam'], best: 0 },
        { label: 'Built for', values: ['Clusters', 'Everything', 'AI on Ethernet'] },
      ],
      fullCompareId: 'infiniband-ethernet-spectrumx',
    },
    related: ['ethernet-road', 'spectrum-x-control', 'rdma', 'dropped-parcels'],
    anchorId: 'infiniband',
    netSim: { network: 'infiniband' },
  },
  {
    id: 'ethernet-road',
    zone,
    kind: 'object',
    number: 4,
    name: 'Ethernet road',
    aliases: ['Ethernet', 'Ethernet for AI'],
    category: 'Network',
    metaphor: 'A public road shared with everyone',
    swatch: 'scene-path',
    summary:
      'Ethernet is the network the rest of the world runs on, and it can carry AI traffic. But running AI on Ethernet needs careful attention to bandwidth, latency and congestion: when the road jams, a classic Ethernet network drops parcels and the sender has to notice and send them again.',
    facts: [{ label: 'ConnectX-7', value: 'up to 400 Gb/s' }],
    compare: {
      with: ['InfiniBand', 'Spectrum-X'],
      rows: [
        { label: 'In the factory', values: ['Public road', 'Private freight rail', 'Road with smart traffic control'] },
        { label: 'When crowded', values: ['Drops parcels and re-sends', 'Waits, never drops', 'Steers round the jam'], best: 1 },
        { label: 'Built for', values: ['Everything', 'Clusters', 'AI on Ethernet'] },
      ],
      fullCompareId: 'infiniband-ethernet-spectrumx',
    },
    related: ['infiniband', 'spectrum-x-control', 'dropped-parcels', 'roce'],
    anchorId: 'ethernet-road',
    netSim: { network: 'ethernet' },
  },
  {
    id: 'dropped-parcels',
    zone,
    kind: 'object',
    number: 5,
    name: 'Dropped parcels',
    aliases: ['packet loss', 'retransmission', 'lost packets'],
    category: 'Network',
    metaphor: 'Crates that fall off the road and must be sent again',
    swatch: 'scene-parcel-hot',
    summary:
      'When a lane is overloaded, a classic network throws away what does not fit. The sender notices the gap and sends the parcel again, and a training job waits for the slowest parcel, so a few drops can slow every GPU in the job.',
    facts: [{ label: 'Lossless by design', value: 'InfiniBand' }],
    related: ['ethernet-road', 'infiniband', 'spectrum-x-control', 'roce'],
    anchorId: 'dropped-parcels',
    netSim: { network: 'ethernet' },
  },
  {
    id: 'spectrum-x-control',
    zone,
    kind: 'object',
    number: 6,
    name: 'Spectrum-X control',
    aliases: ['Spectrum-X', 'adaptive routing', 'Ethernet platform for AI'],
    category: 'Network',
    metaphor: 'A road with smart traffic control',
    swatch: 'scene-coolant',
    summary:
      'Spectrum-X is an Ethernet platform tuned for AI. Adaptive routing sends parcels down whichever lane is free, and congestion control tells senders to ease off before queues overflow, so Ethernet behaves much more like a managed rail while staying Ethernet.',
    facts: [{ label: 'Key ideas', value: 'Adaptive routing and congestion control' }],
    compare: {
      with: ['InfiniBand', 'Ethernet'],
      rows: [
        { label: 'In the factory', values: ['Road with smart traffic control', 'Private freight rail', 'Public road'] },
        { label: 'When crowded', values: ['Steers round the jam', 'Waits, never drops', 'Drops parcels and re-sends'] },
        { label: 'Built for', values: ['AI on Ethernet', 'Clusters', 'Everything'] },
      ],
      fullCompareId: 'infiniband-ethernet-spectrumx',
    },
    related: ['ethernet-road', 'infiniband', 'roce', 'dropped-parcels'],
    anchorId: 'spectrum-x-control',
    netSim: { network: 'spectrumx' },
  },
  {
    id: 'rdma',
    zone,
    kind: 'concept',
    name: 'RDMA',
    aliases: ['remote direct memory access'],
    category: 'Network',
    metaphor: 'Delivery straight to the shelf, skipping the front office',
    summary:
      'RDMA lets one machine read or write another machine\'s memory over the network without the CPUs and operating systems copying the data at each end. It cuts delay and leaves the CPU free, which is why cluster networks are built around it.',
    facts: [{ label: 'Runs over', value: 'InfiniBand or Ethernet (RoCE)' }],
    related: ['roce', 'gpudirect-rdma', 'infiniband', 'dpu-gatehouse'],
  },
  {
    id: 'roce',
    zone,
    kind: 'concept',
    name: 'RoCE',
    aliases: ['RDMA over Converged Ethernet'],
    category: 'Network',
    metaphor: 'Direct-to-shelf delivery on the public road',
    summary:
      'RoCE carries RDMA over Ethernet instead of InfiniBand. It works best on an Ethernet network that has been tuned to lose almost nothing, which is the job platforms such as Spectrum-X take on.',
    facts: [{ label: 'Short for', value: 'RDMA over Converged Ethernet' }],
    related: ['rdma', 'ethernet-road', 'spectrum-x-control'],
  },
  {
    id: 'gpudirect-rdma',
    zone,
    kind: 'concept',
    name: 'GPUDirect RDMA',
    aliases: ['GPU Direct RDMA'],
    category: 'Network',
    metaphor: 'The loading dock opens straight onto the production hall',
    summary:
      'With GPUDirect RDMA the network card reads and writes GPU memory directly, instead of parcels being unpacked into CPU memory first and then repacked for the GPU. It removes a stop from every trip.',
    facts: [{ label: 'Path', value: 'Network card ↔ GPU memory, without staging in CPU memory' }],
    related: ['rdma', 'dgx-node', 'gpudirect-storage'],
  },
  {
    id: 'four-cluster-networks',
    zone,
    kind: 'concept',
    name: 'Four cluster networks',
    aliases: ['compute fabric', 'storage fabric', 'management network'],
    category: 'Architecture',
    metaphor: 'Separate roads for freight, warehouse runs and the staff',
    summary:
      'A cluster does not put everything on one network. GPU traffic gets its own compute network, storage traffic its own storage network, and two management networks keep the staff able to reach every machine even when the freight lanes are busy.',
    facts: [{ label: 'The networks', value: 'Compute, storage, in-band management, out-of-band management' }],
    related: ['infiniband', 'dgx-node', 'ethernet-road'],
  },
];
